### ISSUE TITLE
Eudora

### ISSUE THREAD

**Issue by skipwalker4** [missive/a-timeline-of-email-clients#2]
First email client I ever used outside of AOL

https://en.wikipedia.org/wiki/Eudora_(email_client)

**Comment by EtienneLem** [comment]
Hi there!
Thanks for reporting, however Eudora is already included. See the following screenshot.
![screen shot 2015-12-14 at 12 41 49 pm](https://cloud.githubusercontent.com/assets/436043/11788904/5804093c-a261-11e5-9285-3e08d6bb16bc.png)

Finding a specific email client isn’t an obvious task, we’ll try to come up with a solution where a given email client is easily findable/highlightable.
